# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='login_reg.User')),
                ('user_join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_trips', to='login_reg.User')),
            ],
        ),
    ]
