# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20190222_0934'),
        ('trip', '0002_auto_20190222_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user_join',
        ),
        migrations.AddField(
            model_name='trip',
            name='user_join',
            field=models.ManyToManyField(null=True, related_name='join_trips', to='login_reg.User'),
        ),
    ]
